batch_size_training: 1
bf16: true
c_thought: 1
coconut: true
cot: false
debug: false
epochs_per_stage: 2
eval_do_sample: true
eval_max_new_tokens: 2048
eval_temperature: 0.7
eval_top_k: null
eval_top_p: 0.8
gradient_accumulation_steps: 64
load_model_path: /mnt/disk/coconut/models/coconut-qwen2.5-7b.pt
lr: 5.0e-05
max_latent_stage: 5
model_id: Qwen/Qwen2.5-7B-Instruct
name: coconut-qwen2.5-7b.pt_eval_v0
no_cot: false
no_thoughts: false
num_epochs: 14
only_eval: true
pad_latent_to_max: true
project: coconut
reset_optimizer: true
resume: 10
save_only_improve: false
save_path: /mnt/disk/coconut/checkpoints
seed: 42
torch_compile: false
train_path: ncp_rl_data/your_dataset_train.json
uniform_prob: 0.0
use_boxed_answer: false
use_chat_template: true
use_ddp: false
val_path: ncp_rl_data/your_dataset_test.json
weight_decay: 0.01
