project: coconut
save_path: /mnt/disk/coconut/checkpoints
name: qwen3-ff-smoke-gemma-20260219-201209
only_eval: false
use_ddp: false
smoke_single_gpu: true
torch_compile: false
coconut: true
cot: false
no_thoughts: false
no_cot: false
use_chat_template: true
answer_prefix: "In summary, "
use_boxed_answer: true
c_thought: 1
epochs_per_stage: 1
max_latent_stage: 1
pad_latent_to_max: true
save_only_improve: false
uniform_prob: 0.0
model_id: google/gemma-3-4b-it
load_model_path: None
seed: 42
resume: 0
bf16: true
latent_init_token: '<<'
train_path: ff_data/gemma_smoke_train.json
val_path: ff_data/gemma_smoke_val.json
reset_optimizer: true
batch_size_training: 1
debug: true
gradient_accumulation_steps: 1
num_epochs: 1
lr: 5.0e-05
weight_decay: 0.01
